export type InitialData = 
{
    Pa: number,
    ra: number,
    Lt: number,
    Pb: number,
    rp: number,
    hz: number,
    rf: number,
    Lf: number,
    Pc: number,
    Lm: number,
    Ce: number,
    Ks1: number,
    Uw: number,
    Pu: number,
    Pv: number,
    Pw: number,
    Pz: number,
    Cdb: number,
    Ct: number,
    Cda: number,
    Lc: number,
    Ks2: number,
    p: number,
    H: number,
    L: number,
    W: number,
    Lfv: number,
    Lw: number,
    Ha: number,
    Hc: number,
    La: number,
    Wa: number,
    Td: number,
    Ks3: number
}